# Generated by Django 2.1.2 on 2018-10-03 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('content', models.CharField(max_length=100)),
                ('replay', models.CharField(max_length=100)),
                ('cause', models.CharField(max_length=100)),
                ('solution', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.CharField(max_length=10)),
                ('supporter', models.CharField(max_length=10)),
                ('work', models.TextField()),
                ('status', models.CharField(max_length=10)),
                ('start_date', models.DateField()),
                ('expected_end_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Work'),
        ),
    ]
