# Generated by Django 2.1.2 on 2018-10-04 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='cause',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='issue',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='issue',
            name='replay',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='issue',
            name='solution',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='work',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
