# Generated by Django 2.1.2 on 2018-10-08 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181004_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='status',
            field=models.CharField(default='분석', max_length=10),
        ),
        migrations.AlterField(
            model_name='issue',
            name='cause',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='replay',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='solution',
            field=models.TextField(null=True),
        ),
    ]
